actualizando mi homework
dafevilo/Tareas-G20 pull request #12
Opened 2024-03-13 22:24 UTC by Sughey0803

Por favor revisar mi tarea

2024-03-14 18:59 UTC, dafevilo requested changes
@Sughey0803 por favor agrega la imagen en el readme

2024-03-14 19:31 UTC, DavierRubioQ approved these changes

2024-03-14 23:55 UTC, jorleo021978 commented
a

2024-03-16 02:22 UTC, dafevilo approved these changes

2024-03-16 02:22 UTC, merged