sofia-13-03-24
dafevilo/Tareas-G20 pull request #13
Opened 2024-03-13 23:31 UTC by Sofiapoveda

**_Esta es mi tarea._**

2024-03-13 23:52 UTC, Claudiadiazg commented
![Captura](https://github.com/dafevilo/Tareas-G20/assets/144074982/1bbbb87a-0935-4534-af46-7e1e19cc122a)

2024-03-13 23:53 UTC, Claudiadiazg commented
tarea diagrama de flujo

2024-03-14 00:27 UTC, dafevilo requested changes

2024-03-14 00:27 UTC, dafevilo commented on Tarea_11_03_24/tarea-sofia/README.md
> +Hola Mundo. Esta es mi tarea.
sofia recuerda subir la imagen del diagrama.

2024-03-14 19:03 UTC, dafevilo reviewed
por favor cambia el nombre del pr por el estandar

2024-03-14 19:28 UTC, DavierRubioQ approved these changes

2024-03-18 02:45 UTC, Sofiapoveda commented
> por favor cambia el nombre del pr por el estandar

Hola! Ya cambié el nombre del pull request. No sé si es el correcto. Revisé todos los repositorios para encontrarlo. 
Gracias

2024-03-18 17:04 UTC, YanethCundarM approved these changes
ok

2024-03-18 17:04 UTC, YanethCundarM approved these changes

2024-03-19 02:22 UTC, dafevilo approved these changes

2024-03-19 02:22 UTC, merged