tarea(5): davidEchena-13-03-24
dafevilo/Tareas-G20 pull request #34
Opened 2024-03-18 17:58 UTC by davidleon220

Hola Profesor Daniel, aquí le comparto la tarea del dia 13-03-2024.
No dude en dejarme cualquier comentario, feliz dia.

2024-03-18 23:13 UTC, dafevilo approved these changes

2024-03-18 23:13 UTC, dafevilo commented on Tareas_13_03_24/davidEchena/index.js
> +      divisor.length === 7
@davidleon220 Creo que toda esta logica te sobra

2024-03-19 12:46 UTC, YanethCundarM approved these changes
ok

2024-03-31 20:11 UTC, Claudiadiazg commented
![Captura](https://github.com/dafevilo/Tareas-G20/assets/144074982/c7a3e3c2-1b0a-4c3d-933e-46801c50ae3e)

2024-04-03 01:59 UTC, dafevilo requested changes
@davidleon220 creo que borraste el index donde estaba todo el codigo

2024-04-04 18:00 UTC, closed without merging