tarea(6)-Daniel.esteban.14.03.2024
dafevilo/Tareas-G20 pull request #37
Opened 2024-03-19 00:04 UTC by DanielEstebanLL

Corrección

2024-03-19 02:09 UTC, dafevilo requested changes
@DanielEstebanLL falta de decimal a binario

2024-03-20 01:39 UTC, DanielEstebanLL commented
Hola profe, ya realice los cambios, y complete la tarea

2024-03-20 01:39 UTC, DanielEstebanLL commented
> @DanielEstebanLLfalta de decimal a binario

Hola profe, ya realice los cambios

2024-04-03 02:00 UTC, dafevilo approved these changes

2024-04-03 02:00 UTC, merged