Daniel esteban 12 03 2024
dafevilo/Tareas-G20 pull request #4
Opened 2024-03-13 00:30 UTC by DanielEstebanLL

2024-03-13 01:34 UTC, pabloebaez approved these changes

2024-03-13 01:35 UTC, dafevilo requested changes

2024-03-13 01:35 UTC, dafevilo commented on Tarea_11_03_24/Tarea_Daniel/README.md
> +## Presento mi diagrama de flujo de la demanda
Dani porfa agrega la imagen al readme, para que se vea mucho más organizado

2024-03-15 22:17 UTC, dafevilo approved these changes

2024-03-15 22:17 UTC, merged